#!/bin/bash
echo "🚀 Подготовка к развертыванию..."
echo ""
echo "Скопируйте этот скрипт на сервер и запустите:"
echo ""
echo "1. На вашем компьютере выполните:"
echo "   scp deploy-frontend-timeweb.sh root@89.169.1.238:/tmp/"
echo ""
echo "2. Подключитесь к серверу:"
echo "   ssh root@89.169.1.238"
echo ""
echo "3. Запустите скрипт:"
echo "   chmod +x /tmp/deploy-frontend-timeweb.sh"
echo "   /tmp/deploy-frontend-timeweb.sh"
echo ""
echo "Или используйте прямую ссылку:"
echo "   curl -sSL https://raw.githubusercontent.com/ahmed11551/parcel-pal-08/main/deploy-frontend-timeweb.sh | bash"
